'use strict';

/**
 * src/services/emailService.js
 *
 * Nodemailer wrapper for all transactional emails.
 * Supports two email types required in Phase 1:
 *   1. sendLockoutAlert       — Dispatched when account is locked after 10 failed login attempts
 *   2. sendTemporaryPassword  — Dispatched during forgot-password flow (MVP: send generated password)
 *
 * Transport is configured from environment variables via src/config/env.js.
 * In test environment, emails are silently swallowed (no-op).
 */

const nodemailer = require('nodemailer');
const { config } = require('../config/env');

/**
 * Creates and returns a configured Nodemailer transporter.
 * Reuses the same transporter instance per process lifetime.
 */
let _transporter = null;

function getTransporter() {
  if (_transporter) return _transporter;

  if (process.env.NODE_ENV === 'test') {
    // Test environment: use Nodemailer's built-in test account (swallows emails)
    _transporter = {
      sendMail: async () => ({ messageId: 'test-message-id' }),
    };
    return _transporter;
  }

  _transporter = nodemailer.createTransport({
    host: config.email.host,
    port: config.email.port,
    secure: config.email.secure,
    auth: {
      user: config.email.user,
      pass: config.email.pass,
    },
  });

  return _transporter;
}

/**
 * Sends a security lockout alert email to the user whose account has been locked.
 *
 * @param {string} email  - The recipient's email address
 * @param {string} name   - The recipient's full name (for personalisation)
 */
async function sendLockoutAlert(email, name) {
  const transporter = getTransporter();

  const html = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <h2 style="color: #d32f2f;">⚠️ Account Security Alert — AutoServicePal</h2>
      <p>Hi ${name || 'there'},</p>
      <p>
        Your AutoServicePal account (<strong>${email}</strong>) has been temporarily locked due to
        <strong>10 consecutive failed login attempts</strong>.
      </p>
      <p>
        Your account will be automatically unlocked after <strong>24 hours</strong>.
      </p>
      <p>
        If you did not attempt these logins, your account may be under a brute-force attack.
        Please contact us immediately at <a href="mailto:support@autoservicepal.com">support@autoservicepal.com</a>.
      </p>
      <hr />
      <p style="color: #757575; font-size: 12px;">
        AutoServicePal Security Team — This is an automated message, please do not reply.
      </p>
    </div>
  `;

  await transporter.sendMail({
    from: config.email.from,
    to: email,
    subject: '⚠️ Your AutoServicePal account has been locked',
    html,
  });
}

/**
 * Sends a temporary password to the user during the forgot-password flow.
 * The user is advised to change their password immediately after logging in.
 *
 * @param {string} email           - The recipient's email address
 * @param {string} name            - The recipient's full name
 * @param {string} tempPassword    - The plaintext temporary password (generated by authController)
 */
async function sendTemporaryPassword(email, name, tempPassword) {
  const transporter = getTransporter();

  const html = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <h2 style="color: #1565c0;">AutoServicePal — Password Reset</h2>
      <p>Hi ${name || 'there'},</p>
      <p>We received a request to reset your password. Your temporary password is:</p>
      <div style="
        background: #f5f5f5;
        border: 1px solid #e0e0e0;
        border-radius: 4px;
        padding: 16px;
        font-size: 20px;
        font-family: monospace;
        letter-spacing: 2px;
        text-align: center;
        margin: 16px 0;
      ">
        <strong>${tempPassword}</strong>
      </div>
      <p>
        ⚠️ <strong>Please log in immediately and change this password</strong> from your account settings.
      </p>
      <p>
        If you did not request a password reset, please contact us at
        <a href="mailto:support@autoservicepal.com">support@autoservicepal.com</a> immediately.
      </p>
      <hr />
      <p style="color: #757575; font-size: 12px;">
        AutoServicePal Security Team — This is an automated message, please do not reply.
      </p>
    </div>
  `;

  await transporter.sendMail({
    from: config.email.from,
    to: email,
    subject: 'Your AutoServicePal temporary password',
    html,
  });
}

/**
 * Sends a welcome email to newly registered users.
 *
 * @param {string} email - The recipient's email address
 * @param {string} name  - The recipient's full name
 */
async function sendWelcomeEmail(email, name) {
  const transporter = getTransporter();

  const html = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <h2 style="color: #1565c0;">Welcome to AutoServicePal!</h2>
      <p>Hi ${name || 'there'},</p>
      <p>Thank you for registering an account with us.</p>
      <p>You can now log in, add vehicles, upload V5 documents for verification, and start tracking your service history.</p>
      <br/>
      <p>Happy Motoring!</p>
      <p>The AutoServicePal Team</p>
    </div>
  `;

  await transporter.sendMail({
    from: config.email.from,
    to: email,
    subject: 'Welcome to AutoServicePal',
    html,
  });
}

/**
 * Sends an email notification about V5 verification outcome.
 *
 * @param {string} email - The recipient's email address
 * @param {string} status - 'APPROVED' or 'REJECTED'
 * @param {string} vehicleName - The make/model of the vehicle
 * @param {string} [reason] - Rejection reason if rejected
 */
async function sendV5VerificationEmail(email, status, vehicleName, reason) {
  const transporter = getTransporter();
  
  const isApproved = status === 'APPROVED';
  
  const html = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <h2 style="color: ${isApproved ? '#00E676' : '#E53935'};">V5 Logbook Verification Update</h2>
      <p>Hi there,</p>
      <p>The V5 logbook you uploaded for your <strong>${vehicleName || 'vehicle'}</strong> has been reviewed.</p>
      
      <p>Status: <strong style="color: ${isApproved ? '#00E676' : '#E53935'}">${isApproved ? 'VERIFIED' : 'REJECTED'}</strong></p>
      
      ${!isApproved && reason ? `<p><strong>Reason for rejection:</strong> ${reason}</p>` : ''}
      
      <p>${isApproved ? 'Your vehicle will now display a verified green tick!' : 'Please ensure the image is clear and the full front page is visible before trying again.'}</p>
      
      <br/>
      <p>The AutoServicePal Team</p>
    </div>
  `;

  await transporter.sendMail({
    from: config.email.from,
    to: email,
    subject: `V5 Verification ${isApproved ? 'Successful' : 'Rejected'}`,
    html,
  });
}

module.exports = {
  sendLockoutAlert,
  sendTemporaryPassword,
  sendWelcomeEmail,
  sendV5VerificationEmail,
};
